using System.Text;
using MigraDocCore.DocumentObjectModel.Generators.Model;

namespace MigraDocCore.DocumentObjectModel.Generators;

/// <summary>
/// Turns models into source. Deliberately free of Roslyn types, so it can be exercised with
/// hand-built models and no compilation at all.
/// </summary>
internal static class Emitter
{
    const string Internals = "global::MigraDocCore.DocumentObjectModel.Internals";
    const string Dom = "global::MigraDocCore.DocumentObjectModel.DocumentObject";

    public static string Emit(DomTypeModel type)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable disable");
        source.AppendLine();

        if (type.Namespace.Length > 0)
        {
            source.Append("namespace ").Append(type.Namespace).AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial class ").AppendLine(type.Name);
        source.AppendLine("{");
        source.AppendLine("    /// <summary>The compile-time value model for this type.</summary>");
        source.AppendLine("    /// <remarks>");
        source.AppendLine("    /// A static readonly field, so the CLR's type initializer guarantees it is built once and");
        source.AppendLine("    /// complete before any thread reads it. The hand-written accessor this replaced tested a");
        source.AppendLine("    /// static for null and assigned it without synchronisation, in all 67 DOM classes.");
        source.AppendLine("    ///");
        source.AppendLine("    /// Private, so that a derived DOM class declaring its own does not hide this one (CS0108).");
        source.AppendLine("    /// Reached through the Meta property below, which is what every caller uses anyway.");
        source.AppendLine("    /// </remarks>");
        source.Append("    private static readonly ").Append(Internals).AppendLine(".Meta GeneratedMeta = new(");

        for (int i = 0; i < type.Members.Count; i++)
        {
            EmitDescriptor(source, type, type.Members[i]);
            source.AppendLine(i == type.Members.Count - 1 ? ");" : ",");
        }
        if (type.Members.Count == 0)
            source.AppendLine("        );");

        source.AppendLine();
        source.Append("    internal override ").Append(Internals).AppendLine(".Meta Meta => GeneratedMeta;");
        source.AppendLine("}");
        return source.ToString();
    }

    static void EmitDescriptor(StringBuilder source, DomTypeModel type, DomMemberModel member)
    {
        string self = $"(({type.Name})o)";

        source.Append("        new ").Append(Internals).AppendLine(".ValueDescriptor(");
        source.Append("            valueName: \"").Append(member.Name).AppendLine("\",");
        source.Append("            valueType: typeof(").Append(member.ValueTypeFqn).AppendLine("),");
        source.Append("            memberType: typeof(").Append(member.MemberTypeFqn).AppendLine("),");
        source.Append("            kind: ").Append(Internals).Append(".ValueKind.").Append(member.Kind).AppendLine(",");
        source.Append("            isRefOnly: ").Append(member.IsRefOnly ? "true" : "false").AppendLine(",");

        // Boxing is inherent to the object-based model API, but the reflection it replaces boxed
        // too - and additionally allocated for the FieldInfo.GetValue call itself.
        source.Append("            getter: static o => ").Append(self).Append('.').Append(member.Name).AppendLine(",");

        if (member.IsWritable && member.IsEnum)
        {
            // An enum member takes a boxed int as well as a boxed enum. NEnum stored the value as
            // an int and its setter took one, so SetValue("Style", (int)BorderStyle.Dot) worked
            // through the public model API; a straight cast to BorderStyle? throws
            // InvalidCastException on it. Unboxing has to name the boxed type exactly, hence the
            // test rather than one cast that covers both.
            source.Append("            setter: static (o, v) => ").Append(self).Append('.').Append(member.Name)
                  .Append(" = (").Append(member.MemberTypeFqn).Append(")(v is int ? (")
                  .Append(member.ValueTypeFqn).AppendLine(")(int)v : v),");
        }
        else if (member.IsWritable)
        {
            source.Append("            setter: static (o, v) => ").Append(self).Append('.').Append(member.Name)
                  .Append(" = (").Append(member.MemberTypeFqn).AppendLine(")v,");
        }
        else
        {
            source.AppendLine("            setter: null,");
        }

        if (member.CanConstruct)
            source.Append("            factory: static () => new ").Append(member.MemberTypeFqn).AppendLine("(),");
        else
            source.AppendLine("            factory: null,");

        if (member.BoxedDefaultExpression is not null)
            source.Append("            valueWhenNull: ").Append(member.BoxedDefaultExpression).AppendLine(",");
        else
            source.AppendLine("            valueWhenNull: null,");

        source.Append("            isField: ").Append(member.IsField ? "true" : "false").Append(')');
    }
}
