// <auto-generated>
//   Generated from the Unicode Character Database 17.0.0 by tools/UnicodeTableGenerator.
//   Do not edit by hand. See BidiClass.g.cs for how to regenerate.
// </auto-generated>

namespace PdfSharpCore.Text;

static partial class UnicodeTables
{
    /// <summary>The version of the Unicode Character Database these tables were built from.</summary>
    public const string UnicodeVersion = "17.0.0";
}
