// <auto-generated>
//   Generated from the Unicode Character Database 17.0.0 by tools/UnicodeTableGenerator.
//   Do not edit by hand. To regenerate after a Unicode version bump:
//
//       dotnet run --project tools/UnicodeTableGenerator -- --version 17.0.0 --out PdfSharpCore/Text
//
//   The tool is deliberately outside PdfSharpCore.slnx: it runs by hand, and what it writes is
//   checked in so that the build needs no network and a version bump is a reviewable diff.
// </auto-generated>

namespace PdfSharpCore.Text;

/// <summary>
/// The Script property of a character, as UAX #24 names it.
/// </summary>
public enum UnicodeScript : byte
{
    /// <summary>Adlam</summary>
    Adlam = 0,

    /// <summary>Ahom</summary>
    Ahom = 1,

    /// <summary>Anatolian_Hieroglyphs</summary>
    Anatolian_Hieroglyphs = 2,

    /// <summary>Arabic</summary>
    Arabic = 3,

    /// <summary>Armenian</summary>
    Armenian = 4,

    /// <summary>Avestan</summary>
    Avestan = 5,

    /// <summary>Balinese</summary>
    Balinese = 6,

    /// <summary>Bamum</summary>
    Bamum = 7,

    /// <summary>Bassa_Vah</summary>
    Bassa_Vah = 8,

    /// <summary>Batak</summary>
    Batak = 9,

    /// <summary>Bengali</summary>
    Bengali = 10,

    /// <summary>Beria_Erfe</summary>
    Beria_Erfe = 11,

    /// <summary>Bhaiksuki</summary>
    Bhaiksuki = 12,

    /// <summary>Bopomofo</summary>
    Bopomofo = 13,

    /// <summary>Brahmi</summary>
    Brahmi = 14,

    /// <summary>Braille</summary>
    Braille = 15,

    /// <summary>Buginese</summary>
    Buginese = 16,

    /// <summary>Buhid</summary>
    Buhid = 17,

    /// <summary>Canadian_Aboriginal</summary>
    Canadian_Aboriginal = 18,

    /// <summary>Carian</summary>
    Carian = 19,

    /// <summary>Caucasian_Albanian</summary>
    Caucasian_Albanian = 20,

    /// <summary>Chakma</summary>
    Chakma = 21,

    /// <summary>Cham</summary>
    Cham = 22,

    /// <summary>Cherokee</summary>
    Cherokee = 23,

    /// <summary>Chorasmian</summary>
    Chorasmian = 24,

    /// <summary>Common</summary>
    Common = 25,

    /// <summary>Coptic</summary>
    Coptic = 26,

    /// <summary>Cuneiform</summary>
    Cuneiform = 27,

    /// <summary>Cypriot</summary>
    Cypriot = 28,

    /// <summary>Cypro_Minoan</summary>
    Cypro_Minoan = 29,

    /// <summary>Cyrillic</summary>
    Cyrillic = 30,

    /// <summary>Deseret</summary>
    Deseret = 31,

    /// <summary>Devanagari</summary>
    Devanagari = 32,

    /// <summary>Dives_Akuru</summary>
    Dives_Akuru = 33,

    /// <summary>Dogra</summary>
    Dogra = 34,

    /// <summary>Duployan</summary>
    Duployan = 35,

    /// <summary>Egyptian_Hieroglyphs</summary>
    Egyptian_Hieroglyphs = 36,

    /// <summary>Elbasan</summary>
    Elbasan = 37,

    /// <summary>Elymaic</summary>
    Elymaic = 38,

    /// <summary>Ethiopic</summary>
    Ethiopic = 39,

    /// <summary>Garay</summary>
    Garay = 40,

    /// <summary>Georgian</summary>
    Georgian = 41,

    /// <summary>Glagolitic</summary>
    Glagolitic = 42,

    /// <summary>Gothic</summary>
    Gothic = 43,

    /// <summary>Grantha</summary>
    Grantha = 44,

    /// <summary>Greek</summary>
    Greek = 45,

    /// <summary>Gujarati</summary>
    Gujarati = 46,

    /// <summary>Gunjala_Gondi</summary>
    Gunjala_Gondi = 47,

    /// <summary>Gurmukhi</summary>
    Gurmukhi = 48,

    /// <summary>Gurung_Khema</summary>
    Gurung_Khema = 49,

    /// <summary>Han</summary>
    Han = 50,

    /// <summary>Hangul</summary>
    Hangul = 51,

    /// <summary>Hanifi_Rohingya</summary>
    Hanifi_Rohingya = 52,

    /// <summary>Hanunoo</summary>
    Hanunoo = 53,

    /// <summary>Hatran</summary>
    Hatran = 54,

    /// <summary>Hebrew</summary>
    Hebrew = 55,

    /// <summary>Hiragana</summary>
    Hiragana = 56,

    /// <summary>Imperial_Aramaic</summary>
    Imperial_Aramaic = 57,

    /// <summary>Inherited</summary>
    Inherited = 58,

    /// <summary>Inscriptional_Pahlavi</summary>
    Inscriptional_Pahlavi = 59,

    /// <summary>Inscriptional_Parthian</summary>
    Inscriptional_Parthian = 60,

    /// <summary>Javanese</summary>
    Javanese = 61,

    /// <summary>Kaithi</summary>
    Kaithi = 62,

    /// <summary>Kannada</summary>
    Kannada = 63,

    /// <summary>Katakana</summary>
    Katakana = 64,

    /// <summary>Katakana_Or_Hiragana</summary>
    Katakana_Or_Hiragana = 65,

    /// <summary>Kawi</summary>
    Kawi = 66,

    /// <summary>Kayah_Li</summary>
    Kayah_Li = 67,

    /// <summary>Kharoshthi</summary>
    Kharoshthi = 68,

    /// <summary>Khitan_Small_Script</summary>
    Khitan_Small_Script = 69,

    /// <summary>Khmer</summary>
    Khmer = 70,

    /// <summary>Khojki</summary>
    Khojki = 71,

    /// <summary>Khudawadi</summary>
    Khudawadi = 72,

    /// <summary>Kirat_Rai</summary>
    Kirat_Rai = 73,

    /// <summary>Lao</summary>
    Lao = 74,

    /// <summary>Latin</summary>
    Latin = 75,

    /// <summary>Lepcha</summary>
    Lepcha = 76,

    /// <summary>Limbu</summary>
    Limbu = 77,

    /// <summary>Linear_A</summary>
    Linear_A = 78,

    /// <summary>Linear_B</summary>
    Linear_B = 79,

    /// <summary>Lisu</summary>
    Lisu = 80,

    /// <summary>Lycian</summary>
    Lycian = 81,

    /// <summary>Lydian</summary>
    Lydian = 82,

    /// <summary>Mahajani</summary>
    Mahajani = 83,

    /// <summary>Makasar</summary>
    Makasar = 84,

    /// <summary>Malayalam</summary>
    Malayalam = 85,

    /// <summary>Mandaic</summary>
    Mandaic = 86,

    /// <summary>Manichaean</summary>
    Manichaean = 87,

    /// <summary>Marchen</summary>
    Marchen = 88,

    /// <summary>Masaram_Gondi</summary>
    Masaram_Gondi = 89,

    /// <summary>Medefaidrin</summary>
    Medefaidrin = 90,

    /// <summary>Meetei_Mayek</summary>
    Meetei_Mayek = 91,

    /// <summary>Mende_Kikakui</summary>
    Mende_Kikakui = 92,

    /// <summary>Meroitic_Cursive</summary>
    Meroitic_Cursive = 93,

    /// <summary>Meroitic_Hieroglyphs</summary>
    Meroitic_Hieroglyphs = 94,

    /// <summary>Miao</summary>
    Miao = 95,

    /// <summary>Modi</summary>
    Modi = 96,

    /// <summary>Mongolian</summary>
    Mongolian = 97,

    /// <summary>Mro</summary>
    Mro = 98,

    /// <summary>Multani</summary>
    Multani = 99,

    /// <summary>Myanmar</summary>
    Myanmar = 100,

    /// <summary>Nabataean</summary>
    Nabataean = 101,

    /// <summary>Nag_Mundari</summary>
    Nag_Mundari = 102,

    /// <summary>Nandinagari</summary>
    Nandinagari = 103,

    /// <summary>New_Tai_Lue</summary>
    New_Tai_Lue = 104,

    /// <summary>Newa</summary>
    Newa = 105,

    /// <summary>Nko</summary>
    Nko = 106,

    /// <summary>Nushu</summary>
    Nushu = 107,

    /// <summary>Nyiakeng_Puachue_Hmong</summary>
    Nyiakeng_Puachue_Hmong = 108,

    /// <summary>Ogham</summary>
    Ogham = 109,

    /// <summary>Ol_Chiki</summary>
    Ol_Chiki = 110,

    /// <summary>Ol_Onal</summary>
    Ol_Onal = 111,

    /// <summary>Old_Hungarian</summary>
    Old_Hungarian = 112,

    /// <summary>Old_Italic</summary>
    Old_Italic = 113,

    /// <summary>Old_North_Arabian</summary>
    Old_North_Arabian = 114,

    /// <summary>Old_Permic</summary>
    Old_Permic = 115,

    /// <summary>Old_Persian</summary>
    Old_Persian = 116,

    /// <summary>Old_Sogdian</summary>
    Old_Sogdian = 117,

    /// <summary>Old_South_Arabian</summary>
    Old_South_Arabian = 118,

    /// <summary>Old_Turkic</summary>
    Old_Turkic = 119,

    /// <summary>Old_Uyghur</summary>
    Old_Uyghur = 120,

    /// <summary>Oriya</summary>
    Oriya = 121,

    /// <summary>Osage</summary>
    Osage = 122,

    /// <summary>Osmanya</summary>
    Osmanya = 123,

    /// <summary>Pahawh_Hmong</summary>
    Pahawh_Hmong = 124,

    /// <summary>Palmyrene</summary>
    Palmyrene = 125,

    /// <summary>Pau_Cin_Hau</summary>
    Pau_Cin_Hau = 126,

    /// <summary>Phags_Pa</summary>
    Phags_Pa = 127,

    /// <summary>Phoenician</summary>
    Phoenician = 128,

    /// <summary>Psalter_Pahlavi</summary>
    Psalter_Pahlavi = 129,

    /// <summary>Rejang</summary>
    Rejang = 130,

    /// <summary>Runic</summary>
    Runic = 131,

    /// <summary>Samaritan</summary>
    Samaritan = 132,

    /// <summary>Saurashtra</summary>
    Saurashtra = 133,

    /// <summary>Sharada</summary>
    Sharada = 134,

    /// <summary>Shavian</summary>
    Shavian = 135,

    /// <summary>Siddham</summary>
    Siddham = 136,

    /// <summary>Sidetic</summary>
    Sidetic = 137,

    /// <summary>SignWriting</summary>
    SignWriting = 138,

    /// <summary>Sinhala</summary>
    Sinhala = 139,

    /// <summary>Sogdian</summary>
    Sogdian = 140,

    /// <summary>Sora_Sompeng</summary>
    Sora_Sompeng = 141,

    /// <summary>Soyombo</summary>
    Soyombo = 142,

    /// <summary>Sundanese</summary>
    Sundanese = 143,

    /// <summary>Sunuwar</summary>
    Sunuwar = 144,

    /// <summary>Syloti_Nagri</summary>
    Syloti_Nagri = 145,

    /// <summary>Syriac</summary>
    Syriac = 146,

    /// <summary>Tagalog</summary>
    Tagalog = 147,

    /// <summary>Tagbanwa</summary>
    Tagbanwa = 148,

    /// <summary>Tai_Le</summary>
    Tai_Le = 149,

    /// <summary>Tai_Tham</summary>
    Tai_Tham = 150,

    /// <summary>Tai_Viet</summary>
    Tai_Viet = 151,

    /// <summary>Tai_Yo</summary>
    Tai_Yo = 152,

    /// <summary>Takri</summary>
    Takri = 153,

    /// <summary>Tamil</summary>
    Tamil = 154,

    /// <summary>Tangsa</summary>
    Tangsa = 155,

    /// <summary>Tangut</summary>
    Tangut = 156,

    /// <summary>Telugu</summary>
    Telugu = 157,

    /// <summary>Thaana</summary>
    Thaana = 158,

    /// <summary>Thai</summary>
    Thai = 159,

    /// <summary>Tibetan</summary>
    Tibetan = 160,

    /// <summary>Tifinagh</summary>
    Tifinagh = 161,

    /// <summary>Tirhuta</summary>
    Tirhuta = 162,

    /// <summary>Todhri</summary>
    Todhri = 163,

    /// <summary>Tolong_Siki</summary>
    Tolong_Siki = 164,

    /// <summary>Toto</summary>
    Toto = 165,

    /// <summary>Tulu_Tigalari</summary>
    Tulu_Tigalari = 166,

    /// <summary>Ugaritic</summary>
    Ugaritic = 167,

    /// <summary>Unknown</summary>
    Unknown = 168,

    /// <summary>Vai</summary>
    Vai = 169,

    /// <summary>Vithkuqi</summary>
    Vithkuqi = 170,

    /// <summary>Wancho</summary>
    Wancho = 171,

    /// <summary>Warang_Citi</summary>
    Warang_Citi = 172,

    /// <summary>Yezidi</summary>
    Yezidi = 173,

    /// <summary>Yi</summary>
    Yi = 174,

    /// <summary>Zanabazar_Square</summary>
    Zanabazar_Square = 175,
}

static partial class UnicodeTables
{
    /// <summary>
    /// The first code point of each run of equal UnicodeScript, ascending. A complete
    /// partition of U+0000..U+10FFFF, defaults included, so every code point is in
    /// exactly one run and a lookup is one binary search.
    /// </summary>
    internal static readonly int[] UnicodeScriptRangeStart =
    {
        0x0, 0x41, 0x5B, 0x61, 0x7B, 0xAA, 0xAB, 0xBA, 0xBB, 0xC0, 0xD7, 0xD8, 0xF7, 0xF8, 0x2B9,
        0x2E0, 0x2E5, 0x2EA, 0x2EC, 0x300, 0x370, 0x374, 0x375, 0x378, 0x37A, 0x37E, 0x37F, 0x380,
        0x384, 0x385, 0x386, 0x387, 0x388, 0x38B, 0x38C, 0x38D, 0x38E, 0x3A2, 0x3A3, 0x3E2, 0x3F0,
        0x400, 0x485, 0x487, 0x530, 0x531, 0x557, 0x559, 0x58B, 0x58D, 0x590, 0x591, 0x5C8, 0x5D0,
        0x5EB, 0x5EF, 0x5F5, 0x600, 0x605, 0x606, 0x60C, 0x60D, 0x61B, 0x61C, 0x61F, 0x620, 0x640,
        0x641, 0x64B, 0x656, 0x670, 0x671, 0x6DD, 0x6DE, 0x700, 0x70E, 0x70F, 0x74B, 0x74D, 0x750,
        0x780, 0x7B2, 0x7C0, 0x7FB, 0x7FD, 0x800, 0x82E, 0x830, 0x83F, 0x840, 0x85C, 0x85E, 0x85F,
        0x860, 0x86B, 0x870, 0x892, 0x897, 0x8E2, 0x8E3, 0x900, 0x951, 0x955, 0x964, 0x966, 0x980,
        0x984, 0x985, 0x98D, 0x98F, 0x991, 0x993, 0x9A9, 0x9AA, 0x9B1, 0x9B2, 0x9B3, 0x9B6, 0x9BA,
        0x9BC, 0x9C5, 0x9C7, 0x9C9, 0x9CB, 0x9CF, 0x9D7, 0x9D8, 0x9DC, 0x9DE, 0x9DF, 0x9E4, 0x9E6,
        0x9FF, 0xA01, 0xA04, 0xA05, 0xA0B, 0xA0F, 0xA11, 0xA13, 0xA29, 0xA2A, 0xA31, 0xA32, 0xA34,
        0xA35, 0xA37, 0xA38, 0xA3A, 0xA3C, 0xA3D, 0xA3E, 0xA43, 0xA47, 0xA49, 0xA4B, 0xA4E, 0xA51,
        0xA52, 0xA59, 0xA5D, 0xA5E, 0xA5F, 0xA66, 0xA77, 0xA81, 0xA84, 0xA85, 0xA8E, 0xA8F, 0xA92,
        0xA93, 0xAA9, 0xAAA, 0xAB1, 0xAB2, 0xAB4, 0xAB5, 0xABA, 0xABC, 0xAC6, 0xAC7, 0xACA, 0xACB,
        0xACE, 0xAD0, 0xAD1, 0xAE0, 0xAE4, 0xAE6, 0xAF2, 0xAF9, 0xB00, 0xB01, 0xB04, 0xB05, 0xB0D,
        0xB0F, 0xB11, 0xB13, 0xB29, 0xB2A, 0xB31, 0xB32, 0xB34, 0xB35, 0xB3A, 0xB3C, 0xB45, 0xB47,
        0xB49, 0xB4B, 0xB4E, 0xB55, 0xB58, 0xB5C, 0xB5E, 0xB5F, 0xB64, 0xB66, 0xB78, 0xB82, 0xB84,
        0xB85, 0xB8B, 0xB8E, 0xB91, 0xB92, 0xB96, 0xB99, 0xB9B, 0xB9C, 0xB9D, 0xB9E, 0xBA0, 0xBA3,
        0xBA5, 0xBA8, 0xBAB, 0xBAE, 0xBBA, 0xBBE, 0xBC3, 0xBC6, 0xBC9, 0xBCA, 0xBCE, 0xBD0, 0xBD1,
        0xBD7, 0xBD8, 0xBE6, 0xBFB, 0xC00, 0xC0D, 0xC0E, 0xC11, 0xC12, 0xC29, 0xC2A, 0xC3A, 0xC3C,
        0xC45, 0xC46, 0xC49, 0xC4A, 0xC4E, 0xC55, 0xC57, 0xC58, 0xC5B, 0xC5C, 0xC5E, 0xC60, 0xC64,
        0xC66, 0xC70, 0xC77, 0xC80, 0xC8D, 0xC8E, 0xC91, 0xC92, 0xCA9, 0xCAA, 0xCB4, 0xCB5, 0xCBA,
        0xCBC, 0xCC5, 0xCC6, 0xCC9, 0xCCA, 0xCCE, 0xCD5, 0xCD7, 0xCDC, 0xCDF, 0xCE0, 0xCE4, 0xCE6,
        0xCF0, 0xCF1, 0xCF4, 0xD00, 0xD0D, 0xD0E, 0xD11, 0xD12, 0xD45, 0xD46, 0xD49, 0xD4A, 0xD50,
        0xD54, 0xD64, 0xD66, 0xD80, 0xD81, 0xD84, 0xD85, 0xD97, 0xD9A, 0xDB2, 0xDB3, 0xDBC, 0xDBD,
        0xDBE, 0xDC0, 0xDC7, 0xDCA, 0xDCB, 0xDCF, 0xDD5, 0xDD6, 0xDD7, 0xDD8, 0xDE0, 0xDE6, 0xDF0,
        0xDF2, 0xDF5, 0xE01, 0xE3B, 0xE3F, 0xE40, 0xE5C, 0xE81, 0xE83, 0xE84, 0xE85, 0xE86, 0xE8B,
        0xE8C, 0xEA4, 0xEA5, 0xEA6, 0xEA7, 0xEBE, 0xEC0, 0xEC5, 0xEC6, 0xEC7, 0xEC8, 0xECF, 0xED0,
        0xEDA, 0xEDC, 0xEE0, 0xF00, 0xF48, 0xF49, 0xF6D, 0xF71, 0xF98, 0xF99, 0xFBD, 0xFBE, 0xFCD,
        0xFCE, 0xFD5, 0xFD9, 0xFDB, 0x1000, 0x10A0, 0x10C6, 0x10C7, 0x10C8, 0x10CD, 0x10CE, 0x10D0,
        0x10FB, 0x10FC, 0x1100, 0x1200, 0x1249, 0x124A, 0x124E, 0x1250, 0x1257, 0x1258, 0x1259,
        0x125A, 0x125E, 0x1260, 0x1289, 0x128A, 0x128E, 0x1290, 0x12B1, 0x12B2, 0x12B6, 0x12B8,
        0x12BF, 0x12C0, 0x12C1, 0x12C2, 0x12C6, 0x12C8, 0x12D7, 0x12D8, 0x1311, 0x1312, 0x1316,
        0x1318, 0x135B, 0x135D, 0x137D, 0x1380, 0x139A, 0x13A0, 0x13F6, 0x13F8, 0x13FE, 0x1400,
        0x1680, 0x169D, 0x16A0, 0x16EB, 0x16EE, 0x16F9, 0x1700, 0x1716, 0x171F, 0x1720, 0x1735,
        0x1737, 0x1740, 0x1754, 0x1760, 0x176D, 0x176E, 0x1771, 0x1772, 0x1774, 0x1780, 0x17DE,
        0x17E0, 0x17EA, 0x17F0, 0x17FA, 0x1800, 0x1802, 0x1804, 0x1805, 0x1806, 0x181A, 0x1820,
        0x1879, 0x1880, 0x18AB, 0x18B0, 0x18F6, 0x1900, 0x191F, 0x1920, 0x192C, 0x1930, 0x193C,
        0x1940, 0x1941, 0x1944, 0x1950, 0x196E, 0x1970, 0x1975, 0x1980, 0x19AC, 0x19B0, 0x19CA,
        0x19D0, 0x19DB, 0x19DE, 0x19E0, 0x1A00, 0x1A1C, 0x1A1E, 0x1A20, 0x1A5F, 0x1A60, 0x1A7D,
        0x1A7F, 0x1A8A, 0x1A90, 0x1A9A, 0x1AA0, 0x1AAE, 0x1AB0, 0x1ADE, 0x1AE0, 0x1AEC, 0x1B00,
        0x1B4D, 0x1B4E, 0x1B80, 0x1BC0, 0x1BF4, 0x1BFC, 0x1C00, 0x1C38, 0x1C3B, 0x1C4A, 0x1C4D,
        0x1C50, 0x1C80, 0x1C8B, 0x1C90, 0x1CBB, 0x1CBD, 0x1CC0, 0x1CC8, 0x1CD0, 0x1CD3, 0x1CD4,
        0x1CE1, 0x1CE2, 0x1CE9, 0x1CED, 0x1CEE, 0x1CF4, 0x1CF5, 0x1CF8, 0x1CFA, 0x1CFB, 0x1D00,
        0x1D26, 0x1D2B, 0x1D2C, 0x1D5D, 0x1D62, 0x1D66, 0x1D6B, 0x1D78, 0x1D79, 0x1DBF, 0x1DC0,
        0x1E00, 0x1F00, 0x1F16, 0x1F18, 0x1F1E, 0x1F20, 0x1F46, 0x1F48, 0x1F4E, 0x1F50, 0x1F58,
        0x1F59, 0x1F5A, 0x1F5B, 0x1F5C, 0x1F5D, 0x1F5E, 0x1F5F, 0x1F7E, 0x1F80, 0x1FB5, 0x1FB6,
        0x1FC5, 0x1FC6, 0x1FD4, 0x1FD6, 0x1FDC, 0x1FDD, 0x1FF0, 0x1FF2, 0x1FF5, 0x1FF6, 0x1FFF,
        0x2000, 0x200C, 0x200E, 0x2065, 0x2066, 0x2071, 0x2072, 0x2074, 0x207F, 0x2080, 0x208F,
        0x2090, 0x209D, 0x20A0, 0x20C2, 0x20D0, 0x20F1, 0x2100, 0x2126, 0x2127, 0x212A, 0x212C,
        0x2132, 0x2133, 0x214E, 0x214F, 0x2160, 0x2189, 0x218C, 0x2190, 0x242A, 0x2440, 0x244B,
        0x2460, 0x2800, 0x2900, 0x2B74, 0x2B76, 0x2C00, 0x2C60, 0x2C80, 0x2CF4, 0x2CF9, 0x2D00,
        0x2D26, 0x2D27, 0x2D28, 0x2D2D, 0x2D2E, 0x2D30, 0x2D68, 0x2D6F, 0x2D71, 0x2D7F, 0x2D80,
        0x2D97, 0x2DA0, 0x2DA7, 0x2DA8, 0x2DAF, 0x2DB0, 0x2DB7, 0x2DB8, 0x2DBF, 0x2DC0, 0x2DC7,
        0x2DC8, 0x2DCF, 0x2DD0, 0x2DD7, 0x2DD8, 0x2DDF, 0x2DE0, 0x2E00, 0x2E5E, 0x2E80, 0x2E9A,
        0x2E9B, 0x2EF4, 0x2F00, 0x2FD6, 0x2FF0, 0x3005, 0x3006, 0x3007, 0x3008, 0x3021, 0x302A,
        0x302E, 0x3030, 0x3038, 0x303C, 0x3040, 0x3041, 0x3097, 0x3099, 0x309B, 0x309D, 0x30A0,
        0x30A1, 0x30FB, 0x30FD, 0x3100, 0x3105, 0x3130, 0x3131, 0x318F, 0x3190, 0x31A0, 0x31C0,
        0x31E6, 0x31EF, 0x31F0, 0x3200, 0x321F, 0x3220, 0x3260, 0x327F, 0x32D0, 0x32FF, 0x3300,
        0x3358, 0x3400, 0x4DC0, 0x4E00, 0xA000, 0xA48D, 0xA490, 0xA4C7, 0xA4D0, 0xA500, 0xA62C,
        0xA640, 0xA6A0, 0xA6F8, 0xA700, 0xA722, 0xA788, 0xA78B, 0xA7DD, 0xA7F1, 0xA800, 0xA82D,
        0xA830, 0xA83A, 0xA840, 0xA878, 0xA880, 0xA8C6, 0xA8CE, 0xA8DA, 0xA8E0, 0xA900, 0xA92E,
        0xA92F, 0xA930, 0xA954, 0xA95F, 0xA960, 0xA97D, 0xA980, 0xA9CE, 0xA9CF, 0xA9D0, 0xA9DA,
        0xA9DE, 0xA9E0, 0xA9FF, 0xAA00, 0xAA37, 0xAA40, 0xAA4E, 0xAA50, 0xAA5A, 0xAA5C, 0xAA60,
        0xAA80, 0xAAC3, 0xAADB, 0xAAE0, 0xAAF7, 0xAB01, 0xAB07, 0xAB09, 0xAB0F, 0xAB11, 0xAB17,
        0xAB20, 0xAB27, 0xAB28, 0xAB2F, 0xAB30, 0xAB5B, 0xAB5C, 0xAB65, 0xAB66, 0xAB6A, 0xAB6C,
        0xAB70, 0xABC0, 0xABEE, 0xABF0, 0xABFA, 0xAC00, 0xD7A4, 0xD7B0, 0xD7C7, 0xD7CB, 0xD7FC,
        0xF900, 0xFA6E, 0xFA70, 0xFADA, 0xFB00, 0xFB07, 0xFB13, 0xFB18, 0xFB1D, 0xFB37, 0xFB38,
        0xFB3D, 0xFB3E, 0xFB3F, 0xFB40, 0xFB42, 0xFB43, 0xFB45, 0xFB46, 0xFB50, 0xFD3E, 0xFD40,
        0xFDD0, 0xFDF0, 0xFE00, 0xFE10, 0xFE1A, 0xFE20, 0xFE2E, 0xFE30, 0xFE53, 0xFE54, 0xFE67,
        0xFE68, 0xFE6C, 0xFE70, 0xFE75, 0xFE76, 0xFEFD, 0xFEFF, 0xFF00, 0xFF01, 0xFF21, 0xFF3B,
        0xFF41, 0xFF5B, 0xFF66, 0xFF70, 0xFF71, 0xFF9E, 0xFFA0, 0xFFBF, 0xFFC2, 0xFFC8, 0xFFCA,
        0xFFD0, 0xFFD2, 0xFFD8, 0xFFDA, 0xFFDD, 0xFFE0, 0xFFE7, 0xFFE8, 0xFFEF, 0xFFF9, 0xFFFE,
        0x10000, 0x1000C, 0x1000D, 0x10027, 0x10028, 0x1003B, 0x1003C, 0x1003E, 0x1003F, 0x1004E,
        0x10050, 0x1005E, 0x10080, 0x100FB, 0x10100, 0x10103, 0x10107, 0x10134, 0x10137, 0x10140,
        0x1018F, 0x10190, 0x1019D, 0x101A0, 0x101A1, 0x101D0, 0x101FD, 0x101FE, 0x10280, 0x1029D,
        0x102A0, 0x102D1, 0x102E0, 0x102E1, 0x102FC, 0x10300, 0x10324, 0x1032D, 0x10330, 0x1034B,
        0x10350, 0x1037B, 0x10380, 0x1039E, 0x1039F, 0x103A0, 0x103C4, 0x103C8, 0x103D6, 0x10400,
        0x10450, 0x10480, 0x1049E, 0x104A0, 0x104AA, 0x104B0, 0x104D4, 0x104D8, 0x104FC, 0x10500,
        0x10528, 0x10530, 0x10564, 0x1056F, 0x10570, 0x1057B, 0x1057C, 0x1058B, 0x1058C, 0x10593,
        0x10594, 0x10596, 0x10597, 0x105A2, 0x105A3, 0x105B2, 0x105B3, 0x105BA, 0x105BB, 0x105BD,
        0x105C0, 0x105F4, 0x10600, 0x10737, 0x10740, 0x10756, 0x10760, 0x10768, 0x10780, 0x10786,
        0x10787, 0x107B1, 0x107B2, 0x107BB, 0x10800, 0x10806, 0x10808, 0x10809, 0x1080A, 0x10836,
        0x10837, 0x10839, 0x1083C, 0x1083D, 0x1083F, 0x10840, 0x10856, 0x10857, 0x10860, 0x10880,
        0x1089F, 0x108A7, 0x108B0, 0x108E0, 0x108F3, 0x108F4, 0x108F6, 0x108FB, 0x10900, 0x1091C,
        0x1091F, 0x10920, 0x1093A, 0x1093F, 0x10940, 0x1095A, 0x10980, 0x109A0, 0x109B8, 0x109BC,
        0x109D0, 0x109D2, 0x10A00, 0x10A04, 0x10A05, 0x10A07, 0x10A0C, 0x10A14, 0x10A15, 0x10A18,
        0x10A19, 0x10A36, 0x10A38, 0x10A3B, 0x10A3F, 0x10A49, 0x10A50, 0x10A59, 0x10A60, 0x10A80,
        0x10AA0, 0x10AC0, 0x10AE7, 0x10AEB, 0x10AF7, 0x10B00, 0x10B36, 0x10B39, 0x10B40, 0x10B56,
        0x10B58, 0x10B60, 0x10B73, 0x10B78, 0x10B80, 0x10B92, 0x10B99, 0x10B9D, 0x10BA9, 0x10BB0,
        0x10C00, 0x10C49, 0x10C80, 0x10CB3, 0x10CC0, 0x10CF3, 0x10CFA, 0x10D00, 0x10D28, 0x10D30,
        0x10D3A, 0x10D40, 0x10D66, 0x10D69, 0x10D86, 0x10D8E, 0x10D90, 0x10E60, 0x10E7F, 0x10E80,
        0x10EAA, 0x10EAB, 0x10EAE, 0x10EB0, 0x10EB2, 0x10EC2, 0x10EC8, 0x10ED0, 0x10ED9, 0x10EFA,
        0x10F00, 0x10F28, 0x10F30, 0x10F5A, 0x10F70, 0x10F8A, 0x10FB0, 0x10FCC, 0x10FE0, 0x10FF7,
        0x11000, 0x1104E, 0x11052, 0x11076, 0x1107F, 0x11080, 0x110C3, 0x110CD, 0x110CE, 0x110D0,
        0x110E9, 0x110F0, 0x110FA, 0x11100, 0x11135, 0x11136, 0x11148, 0x11150, 0x11177, 0x11180,
        0x111E0, 0x111E1, 0x111F5, 0x11200, 0x11212, 0x11213, 0x11242, 0x11280, 0x11287, 0x11288,
        0x11289, 0x1128A, 0x1128E, 0x1128F, 0x1129E, 0x1129F, 0x112AA, 0x112B0, 0x112EB, 0x112F0,
        0x112FA, 0x11300, 0x11304, 0x11305, 0x1130D, 0x1130F, 0x11311, 0x11313, 0x11329, 0x1132A,
        0x11331, 0x11332, 0x11334, 0x11335, 0x1133A, 0x1133B, 0x1133C, 0x11345, 0x11347, 0x11349,
        0x1134B, 0x1134E, 0x11350, 0x11351, 0x11357, 0x11358, 0x1135D, 0x11364, 0x11366, 0x1136D,
        0x11370, 0x11375, 0x11380, 0x1138A, 0x1138B, 0x1138C, 0x1138E, 0x1138F, 0x11390, 0x113B6,
        0x113B7, 0x113C1, 0x113C2, 0x113C3, 0x113C5, 0x113C6, 0x113C7, 0x113CB, 0x113CC, 0x113D6,
        0x113D7, 0x113D9, 0x113E1, 0x113E3, 0x11400, 0x1145C, 0x1145D, 0x11462, 0x11480, 0x114C8,
        0x114D0, 0x114DA, 0x11580, 0x115B6, 0x115B8, 0x115DE, 0x11600, 0x11645, 0x11650, 0x1165A,
        0x11660, 0x1166D, 0x11680, 0x116BA, 0x116C0, 0x116CA, 0x116D0, 0x116E4, 0x11700, 0x1171B,
        0x1171D, 0x1172C, 0x11730, 0x11747, 0x11800, 0x1183C, 0x118A0, 0x118F3, 0x118FF, 0x11900,
        0x11907, 0x11909, 0x1190A, 0x1190C, 0x11914, 0x11915, 0x11917, 0x11918, 0x11936, 0x11937,
        0x11939, 0x1193B, 0x11947, 0x11950, 0x1195A, 0x119A0, 0x119A8, 0x119AA, 0x119D8, 0x119DA,
        0x119E5, 0x11A00, 0x11A48, 0x11A50, 0x11AA3, 0x11AB0, 0x11AC0, 0x11AF9, 0x11B00, 0x11B0A,
        0x11B60, 0x11B68, 0x11BC0, 0x11BE2, 0x11BF0, 0x11BFA, 0x11C00, 0x11C09, 0x11C0A, 0x11C37,
        0x11C38, 0x11C46, 0x11C50, 0x11C6D, 0x11C70, 0x11C90, 0x11C92, 0x11CA8, 0x11CA9, 0x11CB7,
        0x11D00, 0x11D07, 0x11D08, 0x11D0A, 0x11D0B, 0x11D37, 0x11D3A, 0x11D3B, 0x11D3C, 0x11D3E,
        0x11D3F, 0x11D48, 0x11D50, 0x11D5A, 0x11D60, 0x11D66, 0x11D67, 0x11D69, 0x11D6A, 0x11D8F,
        0x11D90, 0x11D92, 0x11D93, 0x11D99, 0x11DA0, 0x11DAA, 0x11DB0, 0x11DDC, 0x11DE0, 0x11DEA,
        0x11EE0, 0x11EF9, 0x11F00, 0x11F11, 0x11F12, 0x11F3B, 0x11F3E, 0x11F5B, 0x11FB0, 0x11FB1,
        0x11FC0, 0x11FF2, 0x11FFF, 0x12000, 0x1239A, 0x12400, 0x1246F, 0x12470, 0x12475, 0x12480,
        0x12544, 0x12F90, 0x12FF3, 0x13000, 0x13456, 0x13460, 0x143FB, 0x14400, 0x14647, 0x16100,
        0x1613A, 0x16800, 0x16A39, 0x16A40, 0x16A5F, 0x16A60, 0x16A6A, 0x16A6E, 0x16A70, 0x16ABF,
        0x16AC0, 0x16ACA, 0x16AD0, 0x16AEE, 0x16AF0, 0x16AF6, 0x16B00, 0x16B46, 0x16B50, 0x16B5A,
        0x16B5B, 0x16B62, 0x16B63, 0x16B78, 0x16B7D, 0x16B90, 0x16D40, 0x16D7A, 0x16E40, 0x16E9B,
        0x16EA0, 0x16EB9, 0x16EBB, 0x16ED4, 0x16F00, 0x16F4B, 0x16F4F, 0x16F88, 0x16F8F, 0x16FA0,
        0x16FE0, 0x16FE1, 0x16FE2, 0x16FE4, 0x16FE5, 0x16FF0, 0x16FF7, 0x17000, 0x18B00, 0x18CD6,
        0x18CFF, 0x18D00, 0x18D1F, 0x18D80, 0x18DF3, 0x1AFF0, 0x1AFF4, 0x1AFF5, 0x1AFFC, 0x1AFFD,
        0x1AFFF, 0x1B000, 0x1B001, 0x1B120, 0x1B123, 0x1B132, 0x1B133, 0x1B150, 0x1B153, 0x1B155,
        0x1B156, 0x1B164, 0x1B168, 0x1B170, 0x1B2FC, 0x1BC00, 0x1BC6B, 0x1BC70, 0x1BC7D, 0x1BC80,
        0x1BC89, 0x1BC90, 0x1BC9A, 0x1BC9C, 0x1BCA0, 0x1BCA4, 0x1CC00, 0x1CCFD, 0x1CD00, 0x1CEB4,
        0x1CEBA, 0x1CED1, 0x1CEE0, 0x1CEF1, 0x1CF00, 0x1CF2E, 0x1CF30, 0x1CF47, 0x1CF50, 0x1CFC4,
        0x1D000, 0x1D0F6, 0x1D100, 0x1D127, 0x1D129, 0x1D167, 0x1D16A, 0x1D17B, 0x1D183, 0x1D185,
        0x1D18C, 0x1D1AA, 0x1D1AE, 0x1D1EB, 0x1D200, 0x1D246, 0x1D2C0, 0x1D2D4, 0x1D2E0, 0x1D2F4,
        0x1D300, 0x1D357, 0x1D360, 0x1D379, 0x1D400, 0x1D455, 0x1D456, 0x1D49D, 0x1D49E, 0x1D4A0,
        0x1D4A2, 0x1D4A3, 0x1D4A5, 0x1D4A7, 0x1D4A9, 0x1D4AD, 0x1D4AE, 0x1D4BA, 0x1D4BB, 0x1D4BC,
        0x1D4BD, 0x1D4C4, 0x1D4C5, 0x1D506, 0x1D507, 0x1D50B, 0x1D50D, 0x1D515, 0x1D516, 0x1D51D,
        0x1D51E, 0x1D53A, 0x1D53B, 0x1D53F, 0x1D540, 0x1D545, 0x1D546, 0x1D547, 0x1D54A, 0x1D551,
        0x1D552, 0x1D6A6, 0x1D6A8, 0x1D7CC, 0x1D7CE, 0x1D800, 0x1DA8C, 0x1DA9B, 0x1DAA0, 0x1DAA1,
        0x1DAB0, 0x1DF00, 0x1DF1F, 0x1DF25, 0x1DF2B, 0x1E000, 0x1E007, 0x1E008, 0x1E019, 0x1E01B,
        0x1E022, 0x1E023, 0x1E025, 0x1E026, 0x1E02B, 0x1E030, 0x1E06E, 0x1E08F, 0x1E090, 0x1E100,
        0x1E12D, 0x1E130, 0x1E13E, 0x1E140, 0x1E14A, 0x1E14E, 0x1E150, 0x1E290, 0x1E2AF, 0x1E2C0,
        0x1E2FA, 0x1E2FF, 0x1E300, 0x1E4D0, 0x1E4FA, 0x1E5D0, 0x1E5FB, 0x1E5FF, 0x1E600, 0x1E6C0,
        0x1E6DF, 0x1E6E0, 0x1E6F6, 0x1E6FE, 0x1E700, 0x1E7E0, 0x1E7E7, 0x1E7E8, 0x1E7EC, 0x1E7ED,
        0x1E7EF, 0x1E7F0, 0x1E7FF, 0x1E800, 0x1E8C5, 0x1E8C7, 0x1E8D7, 0x1E900, 0x1E94C, 0x1E950,
        0x1E95A, 0x1E95E, 0x1E960, 0x1EC71, 0x1ECB5, 0x1ED01, 0x1ED3E, 0x1EE00, 0x1EE04, 0x1EE05,
        0x1EE20, 0x1EE21, 0x1EE23, 0x1EE24, 0x1EE25, 0x1EE27, 0x1EE28, 0x1EE29, 0x1EE33, 0x1EE34,
        0x1EE38, 0x1EE39, 0x1EE3A, 0x1EE3B, 0x1EE3C, 0x1EE42, 0x1EE43, 0x1EE47, 0x1EE48, 0x1EE49,
        0x1EE4A, 0x1EE4B, 0x1EE4C, 0x1EE4D, 0x1EE50, 0x1EE51, 0x1EE53, 0x1EE54, 0x1EE55, 0x1EE57,
        0x1EE58, 0x1EE59, 0x1EE5A, 0x1EE5B, 0x1EE5C, 0x1EE5D, 0x1EE5E, 0x1EE5F, 0x1EE60, 0x1EE61,
        0x1EE63, 0x1EE64, 0x1EE65, 0x1EE67, 0x1EE6B, 0x1EE6C, 0x1EE73, 0x1EE74, 0x1EE78, 0x1EE79,
        0x1EE7D, 0x1EE7E, 0x1EE7F, 0x1EE80, 0x1EE8A, 0x1EE8B, 0x1EE9C, 0x1EEA1, 0x1EEA4, 0x1EEA5,
        0x1EEAA, 0x1EEAB, 0x1EEBC, 0x1EEF0, 0x1EEF2, 0x1F000, 0x1F02C, 0x1F030, 0x1F094, 0x1F0A0,
        0x1F0AF, 0x1F0B1, 0x1F0C0, 0x1F0C1, 0x1F0D0, 0x1F0D1, 0x1F0F6, 0x1F100, 0x1F1AE, 0x1F1E6,
        0x1F200, 0x1F201, 0x1F203, 0x1F210, 0x1F23C, 0x1F240, 0x1F249, 0x1F250, 0x1F252, 0x1F260,
        0x1F266, 0x1F300, 0x1F6D9, 0x1F6DC, 0x1F6ED, 0x1F6F0, 0x1F6FD, 0x1F700, 0x1F7DA, 0x1F7E0,
        0x1F7EC, 0x1F7F0, 0x1F7F1, 0x1F800, 0x1F80C, 0x1F810, 0x1F848, 0x1F850, 0x1F85A, 0x1F860,
        0x1F888, 0x1F890, 0x1F8AE, 0x1F8B0, 0x1F8BC, 0x1F8C0, 0x1F8C2, 0x1F8D0, 0x1F8D9, 0x1F900,
        0x1FA58, 0x1FA60, 0x1FA6E, 0x1FA70, 0x1FA7D, 0x1FA80, 0x1FA8B, 0x1FA8E, 0x1FAC7, 0x1FAC8,
        0x1FAC9, 0x1FACD, 0x1FADD, 0x1FADF, 0x1FAEB, 0x1FAEF, 0x1FAF9, 0x1FB00, 0x1FB93, 0x1FB94,
        0x1FBFB, 0x20000, 0x2A6E0, 0x2A700, 0x2B81E, 0x2B820, 0x2CEAE, 0x2CEB0, 0x2EBE1, 0x2EBF0,
        0x2EE5E, 0x2F800, 0x2FA1E, 0x30000, 0x3134B, 0x31350, 0x3347A, 0xE0001, 0xE0002, 0xE0020,
        0xE0080, 0xE0100, 0xE01F0,
    };

    /// <summary>The value of each run of <see cref="UnicodeScriptRangeStart"/>.</summary>
    internal static readonly byte[] UnicodeScriptRangeValue =
    {
        25, 75, 25, 75, 25, 75, 25, 75, 25, 75, 25, 75, 25, 75, 25, 75, 25, 13, 25, 58, 45, 25, 45,
        168, 45, 25, 45, 168, 45, 25, 45, 25, 45, 168, 45, 168, 45, 168, 45, 26, 45, 30, 58, 30,
        168, 4, 168, 4, 168, 4, 168, 55, 168, 55, 168, 55, 168, 3, 25, 3, 25, 3, 25, 3, 25, 3, 25,
        3, 58, 3, 58, 3, 25, 3, 146, 168, 146, 168, 146, 3, 158, 168, 106, 168, 106, 132, 168, 132,
        168, 86, 168, 86, 168, 146, 168, 3, 168, 3, 25, 3, 32, 58, 32, 25, 32, 10, 168, 10, 168,
        10, 168, 10, 168, 10, 168, 10, 168, 10, 168, 10, 168, 10, 168, 10, 168, 10, 168, 10, 168,
        10, 168, 10, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168,
        48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 48, 168, 46, 168, 46, 168,
        46, 168, 46, 168, 46, 168, 46, 168, 46, 168, 46, 168, 46, 168, 46, 168, 46, 168, 46, 168,
        46, 168, 46, 168, 121, 168, 121, 168, 121, 168, 121, 168, 121, 168, 121, 168, 121, 168,
        121, 168, 121, 168, 121, 168, 121, 168, 121, 168, 121, 168, 121, 168, 154, 168, 154, 168,
        154, 168, 154, 168, 154, 168, 154, 168, 154, 168, 154, 168, 154, 168, 154, 168, 154, 168,
        154, 168, 154, 168, 154, 168, 154, 168, 154, 168, 157, 168, 157, 168, 157, 168, 157, 168,
        157, 168, 157, 168, 157, 168, 157, 168, 157, 168, 157, 168, 157, 168, 157, 168, 157, 63,
        168, 63, 168, 63, 168, 63, 168, 63, 168, 63, 168, 63, 168, 63, 168, 63, 168, 63, 168, 63,
        168, 63, 168, 63, 168, 85, 168, 85, 168, 85, 168, 85, 168, 85, 168, 85, 168, 85, 168, 139,
        168, 139, 168, 139, 168, 139, 168, 139, 168, 139, 168, 139, 168, 139, 168, 139, 168, 139,
        168, 139, 168, 139, 168, 159, 168, 25, 159, 168, 74, 168, 74, 168, 74, 168, 74, 168, 74,
        168, 74, 168, 74, 168, 74, 168, 74, 168, 74, 168, 74, 168, 160, 168, 160, 168, 160, 168,
        160, 168, 160, 168, 160, 25, 160, 168, 100, 41, 168, 41, 168, 41, 168, 41, 25, 41, 51, 39,
        168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39,
        168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 23, 168, 23, 168, 18,
        109, 168, 131, 25, 131, 168, 147, 168, 147, 53, 25, 168, 17, 168, 148, 168, 148, 168, 148,
        168, 70, 168, 70, 168, 70, 168, 97, 25, 97, 25, 97, 168, 97, 168, 97, 168, 18, 168, 77,
        168, 77, 168, 77, 168, 77, 168, 77, 149, 168, 149, 168, 104, 168, 104, 168, 104, 168, 104,
        70, 16, 168, 16, 150, 168, 150, 168, 150, 168, 150, 168, 150, 168, 58, 168, 58, 168, 6,
        168, 6, 143, 9, 168, 9, 76, 168, 76, 168, 76, 110, 30, 168, 41, 168, 41, 143, 168, 58, 25,
        58, 25, 58, 25, 58, 25, 58, 25, 58, 25, 168, 75, 45, 30, 75, 45, 75, 45, 75, 30, 75, 45,
        58, 75, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168,
        45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 45, 168, 25, 58, 25, 168, 25, 75,
        168, 25, 75, 25, 168, 75, 168, 25, 168, 58, 168, 25, 45, 25, 75, 25, 75, 25, 75, 25, 75,
        25, 168, 25, 168, 25, 168, 25, 15, 25, 168, 25, 42, 75, 26, 168, 26, 41, 168, 41, 168, 41,
        168, 161, 168, 161, 168, 161, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39,
        168, 39, 168, 39, 168, 30, 25, 168, 50, 168, 50, 168, 50, 168, 25, 50, 25, 50, 25, 50, 58,
        51, 25, 50, 25, 168, 56, 168, 58, 25, 56, 25, 64, 25, 64, 168, 13, 168, 51, 168, 25, 13,
        25, 168, 25, 64, 51, 168, 25, 51, 25, 64, 25, 64, 25, 50, 25, 50, 174, 168, 174, 168, 80,
        169, 168, 30, 7, 168, 25, 75, 25, 75, 168, 75, 145, 168, 25, 168, 127, 168, 133, 168, 133,
        168, 32, 67, 25, 67, 130, 168, 130, 51, 168, 61, 168, 25, 61, 168, 61, 100, 168, 22, 168,
        22, 168, 22, 168, 22, 100, 151, 168, 151, 91, 168, 39, 168, 39, 168, 39, 168, 39, 168, 39,
        168, 75, 25, 75, 45, 75, 25, 168, 23, 91, 168, 91, 168, 51, 168, 51, 168, 51, 168, 50, 168,
        50, 168, 75, 168, 4, 168, 55, 168, 55, 168, 55, 168, 55, 168, 55, 168, 55, 3, 25, 3, 168,
        3, 58, 25, 168, 58, 30, 25, 168, 25, 168, 25, 168, 3, 168, 3, 168, 25, 168, 25, 75, 25, 75,
        25, 64, 25, 64, 25, 51, 168, 51, 168, 51, 168, 51, 168, 51, 168, 25, 168, 25, 168, 25, 168,
        79, 168, 79, 168, 79, 168, 79, 168, 79, 168, 79, 168, 79, 168, 25, 168, 25, 168, 25, 45,
        168, 25, 168, 45, 168, 25, 58, 168, 81, 168, 19, 168, 58, 25, 168, 113, 168, 113, 43, 168,
        115, 168, 167, 168, 167, 116, 168, 116, 168, 31, 135, 123, 168, 123, 168, 122, 168, 122,
        168, 37, 168, 20, 168, 20, 170, 168, 170, 168, 170, 168, 170, 168, 170, 168, 170, 168, 170,
        168, 170, 168, 163, 168, 78, 168, 78, 168, 78, 168, 75, 168, 75, 168, 75, 168, 28, 168, 28,
        168, 28, 168, 28, 168, 28, 168, 28, 57, 168, 57, 125, 101, 168, 101, 168, 54, 168, 54, 168,
        54, 128, 168, 128, 82, 168, 82, 137, 168, 94, 93, 168, 93, 168, 93, 68, 168, 68, 168, 68,
        168, 68, 168, 68, 168, 68, 168, 68, 168, 68, 168, 118, 114, 168, 87, 168, 87, 168, 5, 168,
        5, 60, 168, 60, 59, 168, 59, 129, 168, 129, 168, 129, 168, 119, 168, 112, 168, 112, 168,
        112, 52, 168, 52, 168, 40, 168, 40, 168, 40, 168, 3, 168, 173, 168, 173, 168, 173, 168, 3,
        168, 3, 168, 3, 117, 168, 140, 168, 120, 168, 24, 168, 38, 168, 14, 168, 14, 168, 14, 62,
        168, 62, 168, 141, 168, 141, 168, 21, 168, 21, 168, 83, 168, 134, 168, 139, 168, 71, 168,
        71, 168, 99, 168, 99, 168, 99, 168, 99, 168, 99, 168, 72, 168, 72, 168, 44, 168, 44, 168,
        44, 168, 44, 168, 44, 168, 44, 168, 44, 168, 58, 44, 168, 44, 168, 44, 168, 44, 168, 44,
        168, 44, 168, 44, 168, 44, 168, 166, 168, 166, 168, 166, 168, 166, 168, 166, 168, 166, 168,
        166, 168, 166, 168, 166, 168, 166, 168, 166, 168, 105, 168, 105, 168, 162, 168, 162, 168,
        136, 168, 136, 168, 96, 168, 96, 168, 97, 168, 153, 168, 153, 168, 100, 168, 1, 168, 1,
        168, 1, 168, 34, 168, 172, 168, 172, 33, 168, 33, 168, 33, 168, 33, 168, 33, 168, 33, 168,
        33, 168, 33, 168, 103, 168, 103, 168, 103, 168, 175, 168, 142, 168, 18, 126, 168, 32, 168,
        134, 168, 144, 168, 144, 168, 12, 168, 12, 168, 12, 168, 12, 168, 88, 168, 88, 168, 88,
        168, 89, 168, 89, 168, 89, 168, 89, 168, 89, 168, 89, 168, 89, 168, 47, 168, 47, 168, 47,
        168, 47, 168, 47, 168, 47, 168, 164, 168, 164, 168, 84, 168, 66, 168, 66, 168, 66, 168, 80,
        168, 154, 168, 154, 27, 168, 27, 168, 27, 168, 27, 168, 29, 168, 36, 168, 36, 168, 2, 168,
        49, 168, 7, 168, 98, 168, 98, 168, 98, 155, 168, 155, 168, 8, 168, 8, 168, 124, 168, 124,
        168, 124, 168, 124, 168, 124, 168, 73, 168, 90, 168, 11, 168, 11, 168, 95, 168, 95, 168,
        95, 168, 156, 107, 50, 69, 168, 50, 168, 156, 69, 168, 69, 156, 168, 156, 168, 64, 168, 64,
        168, 64, 168, 64, 56, 64, 168, 56, 168, 56, 168, 64, 168, 64, 168, 107, 168, 35, 168, 35,
        168, 35, 168, 35, 168, 35, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 58, 168, 58, 168,
        25, 168, 25, 168, 25, 168, 25, 58, 25, 58, 25, 58, 25, 58, 25, 168, 45, 168, 25, 168, 25,
        168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25,
        168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25,
        168, 25, 168, 25, 168, 25, 138, 168, 138, 168, 138, 168, 75, 168, 75, 168, 42, 168, 42,
        168, 42, 168, 42, 168, 42, 168, 30, 168, 30, 168, 108, 168, 108, 168, 108, 168, 108, 168,
        165, 168, 171, 168, 171, 168, 102, 168, 111, 168, 111, 168, 152, 168, 152, 168, 152, 168,
        39, 168, 39, 168, 39, 168, 39, 168, 92, 168, 92, 168, 0, 168, 0, 168, 0, 168, 25, 168, 25,
        168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3,
        168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3,
        168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3, 168, 3,
        168, 3, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 56, 25,
        168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25,
        168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25,
        168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 25, 168, 50,
        168, 50, 168, 50, 168, 50, 168, 50, 168, 50, 168, 50, 168, 50, 168, 25, 168, 25, 168, 58,
        168,
    };

    /// <summary>
    /// The ISO 15924 code of each <see cref="UnicodeScript"/>, lowercased - the form a
    /// shaper is told a run's script in.
    /// </summary>
    internal static readonly string[] UnicodeScriptCode =
    {
        "adlm", "ahom", "hluw", "arab", "armn", "avst", "bali", "bamu", "bass", "batk", "beng",
        "berf", "bhks", "bopo", "brah", "brai", "bugi", "buhd", "cans", "cari", "aghb", "cakm",
        "cham", "cher", "chrs", "zyyy", "copt", "xsux", "cprt", "cpmn", "cyrl", "dsrt", "deva",
        "diak", "dogr", "dupl", "egyp", "elba", "elym", "ethi", "gara", "geor", "glag", "goth",
        "gran", "grek", "gujr", "gong", "guru", "gukh", "hani", "hang", "rohg", "hano", "hatr",
        "hebr", "hira", "armi", "zinh", "phli", "prti", "java", "kthi", "knda", "kana", "hrkt",
        "kawi", "kali", "khar", "kits", "khmr", "khoj", "sind", "krai", "laoo", "latn", "lepc",
        "limb", "lina", "linb", "lisu", "lyci", "lydi", "mahj", "maka", "mlym", "mand", "mani",
        "marc", "gonm", "medf", "mtei", "mend", "merc", "mero", "plrd", "modi", "mong", "mroo",
        "mult", "mymr", "nbat", "nagm", "nand", "talu", "newa", "nkoo", "nshu", "hmnp", "ogam",
        "olck", "onao", "hung", "ital", "narb", "perm", "xpeo", "sogo", "sarb", "orkh", "ougr",
        "orya", "osge", "osma", "hmng", "palm", "pauc", "phag", "phnx", "phlp", "rjng", "runr",
        "samr", "saur", "shrd", "shaw", "sidd", "sidt", "sgnw", "sinh", "sogd", "sora", "soyo",
        "sund", "sunu", "sylo", "syrc", "tglg", "tagb", "tale", "lana", "tavt", "tayo", "takr",
        "taml", "tnsa", "tang", "telu", "thaa", "thai", "tibt", "tfng", "tirh", "todr", "tols",
        "toto", "tutg", "ugar", "zzzz", "vaii", "vith", "wcho", "wara", "yezi", "yiii", "zanb",
    };
}
