using System.Globalization;
using System.Text;

// Reads the Unicode Character Database and writes the range tables PdfSharpCore.Text looks
// character properties up in. See README.md beside this file.

var version = Argument(args, "--version") ?? "17.0.0";
var cache = Argument(args, "--cache") ?? Path.Combine(Path.GetTempPath(), "ucd-" + version);
var output = Argument(args, "--out") ?? Path.Combine("PdfSharpCore", "Text");

Directory.CreateDirectory(cache);
Directory.CreateDirectory(output);

Console.WriteLine($"Unicode {version}, cache {cache}, out {output}");

// DerivedBidiClass.txt names its values by their short alias ("AL"), Scripts.txt by their long
// name ("Arabic"), and PropertyValueAliases.txt is what reconciles them. Everything below works in
// long names and reaches for the short one only when it needs a code.
var aliases = ReadAliases(await Fetch("ucd/PropertyValueAliases.txt"));
var (bidiToLong, bidiToShort) = aliases["bc"];
var (scriptToLong, scriptToShort) = aliases["sc"];

// ----- Bidi_Class -------------------------------------------------------------------------------

var bidiText = await Fetch("ucd/extracted/DerivedBidiClass.txt");

// The @missing lines are not commentary: DerivedBidiClass.txt lists the assigned characters and
// leaves unassigned ones to defaults that are *not* all Left_To_Right. Unassigned code points in
// the Hebrew and Arabic blocks default to Right_To_Left and Arabic_Letter, and getting that wrong
// makes the algorithm quietly incorrect for exactly the scripts it exists for.
var bidi = Partition(
    Canonical(Defaults(bidiText), bidiToLong),
    Canonical(Ranges(bidiText), bidiToLong),
    fallback: "Left_To_Right");

var bidiNames = OrderedValues(bidi, bidiToShort);
Write(Path.Combine(output, "BidiClass.g.cs"), Emit(
    version, "BidiClass", "byte",
    "The Bidi_Class property of a character, as UAX #9 names it.",
    bidiNames, bidi, bidiToShort, scriptCodes: false));

// ----- Script -----------------------------------------------------------------------------------

var scriptText = await Fetch("ucd/Scripts.txt");
var script = Partition(
    Canonical(Defaults(scriptText), scriptToLong),
    Canonical(Ranges(scriptText), scriptToLong),
    fallback: "Unknown");

var scriptNames = OrderedValues(script, scriptToShort);
Write(Path.Combine(output, "UnicodeScript.g.cs"), Emit(
    version, "UnicodeScript", "byte",
    "The Script property of a character, as UAX #24 names it.",
    scriptNames, script, scriptToShort, scriptCodes: true));

// ----- paired brackets, for rule N0 ---------------------------------------------------------------

// "code; paired code; type", one line per bracket, with the type in a third column that the
// general range reader has no use for.
var bracketText = await Fetch("ucd/BidiBrackets.txt");
var pairs = new List<(int Open, int Close)>();
foreach (var line in Lines(bracketText))
{
    var parts = line.Split(';', StringSplitOptions.TrimEntries);
    if (parts.Length < 3 || parts[2] != "o")
        continue;

    pairs.Add((Convert.ToInt32(parts[0], 16), Convert.ToInt32(parts[1], 16)));
}
pairs.Sort();

Write(Path.Combine(output, "BracketPairs.g.cs"), $@"// <auto-generated>
//   Generated from the Unicode Character Database {version} by tools/UnicodeTableGenerator.
//   Do not edit by hand. See BidiClass.g.cs for how to regenerate.
// </auto-generated>

namespace PdfSharpCore.Text;

static partial class UnicodeTables
{{
    /// <summary>
    /// The opening character of each canonical bracket pair, ascending - the Bidi_Paired_Bracket
    /// property where Bidi_Paired_Bracket_Type is Open. Rule N0 pairs them up.
    /// </summary>
    internal static readonly int[] BracketOpen =
    {{
{Wrap(pairs.Select(p => "0x" + p.Open.ToString("X", CultureInfo.InvariantCulture)))}    }};

    /// <summary>The closing character of each pair of <see cref=""BracketOpen""/>.</summary>
    internal static readonly int[] BracketClose =
    {{
{Wrap(pairs.Select(p => "0x" + p.Close.ToString("X", CultureInfo.InvariantCulture)))}    }};
}}
");

// Its own file, because the tables are partial parts of the same class and only one of them can
// declare it.
Write(Path.Combine(output, "UnicodeVersion.g.cs"), $@"// <auto-generated>
//   Generated from the Unicode Character Database {version} by tools/UnicodeTableGenerator.
//   Do not edit by hand. See BidiClass.g.cs for how to regenerate.
// </auto-generated>

namespace PdfSharpCore.Text;

static partial class UnicodeTables
{{
    /// <summary>The version of the Unicode Character Database these tables were built from.</summary>
    public const string UnicodeVersion = ""{version}"";
}}
");

Console.WriteLine("done");
return 0;

// ----- reading the database ----------------------------------------------------------------------

static string Argument(string[] args, string name)
{
    var idx = Array.IndexOf(args, name);
    return idx >= 0 && idx + 1 < args.Length ? args[idx + 1] : null;
}

async Task<string> Fetch(string path)
{
    var file = Path.Combine(cache, path.Replace('/', '_'));
    if (File.Exists(file))
        return File.ReadAllText(file);

    var url = $"https://www.unicode.org/Public/{version}/{path}";
    Console.WriteLine("fetching " + url);
    using var http = new HttpClient();
    var text = await http.GetStringAsync(url);
    File.WriteAllText(file, text);
    return text;
}

/// <summary>
/// Per property: every spelling of a value to its long name, and every long name to its short
/// alias. A line reads "sc ; Arab ; Arabic", short first and long second, with any further
/// aliases after that.
/// </summary>
static Dictionary<string, (Dictionary<string, string> ToLong, Dictionary<string, string> ToShort)>
    ReadAliases(string text)
{
    var byProperty =
        new Dictionary<string, (Dictionary<string, string>, Dictionary<string, string>)>();

    foreach (var line in Lines(text))
    {
        var parts = line.Split(';', StringSplitOptions.TrimEntries);
        if (parts.Length < 3)
            continue;

        if (!byProperty.TryGetValue(parts[0], out var maps))
            byProperty[parts[0]] = maps = (new Dictionary<string, string>(), new Dictionary<string, string>());

        var (toLong, toShort) = maps;
        var longName = parts[2];

        toShort[longName] = parts[1];
        for (var idx = 1; idx < parts.Length; idx++)
            toLong[parts[idx]] = longName;
    }

    return byProperty;
}

/// <summary>The same ranges with every value spelled as its long name.</summary>
static List<(int First, int Last, string Value)> Canonical(
    IEnumerable<(int First, int Last, string Value)> ranges, Dictionary<string, string> toLong)
    => ranges.Select(r => (r.First, r.Last, toLong.GetValueOrDefault(r.Value, r.Value))).ToList();

static IEnumerable<string> Lines(string text)
{
    foreach (var raw in text.Split('\n'))
    {
        var line = raw.Split('#')[0].Trim();
        if (line.Length > 0)
            yield return line;
    }
}

/// <summary>The explicit ranges of a UCD file, as (first, last, value).</summary>
static IEnumerable<(int First, int Last, string Value)> Ranges(string text)
{
    foreach (var line in Lines(text))
    {
        var parts = line.Split(';', StringSplitOptions.TrimEntries);
        if (parts.Length < 2)
            continue;

        var (first, last) = Span(parts[0]);
        if (first >= 0)
            yield return (first, last, parts[1]);
    }
}

/// <summary>The ranges named on the file's @missing lines, which live inside comments.</summary>
static IEnumerable<(int First, int Last, string Value)> Defaults(string text)
{
    foreach (var raw in text.Split('\n'))
    {
        var idx = raw.IndexOf("@missing:", StringComparison.Ordinal);
        if (idx < 0)
            continue;

        var parts = raw[(idx + "@missing:".Length)..].Split(';', StringSplitOptions.TrimEntries);
        if (parts.Length < 2)
            continue;

        var (first, last) = Span(parts[0]);
        if (first >= 0)
            yield return (first, last, parts[1]);
    }
}

static (int First, int Last) Span(string field)
{
    var halves = field.Split("..");
    if (!int.TryParse(halves[0], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var first))
        return (-1, -1);

    var last = first;
    if (halves.Length > 1)
        int.TryParse(halves[1], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out last);

    return (first, last);
}

// ----- turning them into one complete partition ----------------------------------------------------

/// <summary>
/// Every code point from 0 to 10FFFF given exactly one value, so that a lookup is one binary
/// search with no defaulting left to do at run time.
/// </summary>
static List<(int First, string Value)> Partition(
    List<(int First, int Last, string Value)> defaults,
    List<(int First, int Last, string Value)> explicitly,
    string fallback)
{
    var values = new string[Ucd.MaxCodePoint + 1];
    Array.Fill(values, fallback);

    // Defaults first, widest to narrowest, then every explicit range painted over the lot. Doing
    // it in two passes rather than sorting everything by width is the difference between "an
    // explicit range always wins" and "an explicit range wins as long as it is narrower than the
    // default it overlaps", which is true today and is not a property anyone should have to keep
    // true.
    foreach (var (first, last, value) in defaults.OrderByDescending(r => r.Last - r.First))
        Paint(values, first, last, value);

    foreach (var (first, last, value) in explicitly)
        Paint(values, first, last, value);

    var partition = new List<(int, string)> { (0, values[0]) };
    for (var cp = 1; cp <= Ucd.MaxCodePoint; cp++)
    {
        if (!string.Equals(values[cp], values[cp - 1], StringComparison.Ordinal))
            partition.Add((cp, values[cp]));
    }

    return partition;
}

static void Paint(string[] values, int first, int last, string value)
{
    for (var cp = first; cp <= last && cp <= Ucd.MaxCodePoint; cp++)
        values[cp] = value;
}

static List<string> OrderedValues(
    List<(int First, string Value)> partition, Dictionary<string, string> aliases)
{
    var names = partition.Select(entry => entry.Value).Distinct().ToList();

    // Every value the property defines, not only the ones some character happens to have, so that
    // the enum does not change shape because a Unicode version assigned nothing to a script.
    foreach (var known in aliases.Keys)
    {
        if (!names.Contains(known))
            names.Add(known);
    }

    names.Sort(StringComparer.Ordinal);
    return names;
}

// ----- emitting ------------------------------------------------------------------------------------

static string Emit(string version, string enumName, string storage, string summary,
    List<string> names, List<(int First, string Value)> partition,
    Dictionary<string, string> aliases, bool scriptCodes)
{
    var index = names.Select((name, idx) => (name, idx))
        .ToDictionary(pair => pair.name, pair => pair.idx, StringComparer.Ordinal);

    var sb = new StringBuilder();
    sb.Append($@"// <auto-generated>
//   Generated from the Unicode Character Database {version} by tools/UnicodeTableGenerator.
//   Do not edit by hand. To regenerate after a Unicode version bump:
//
//       dotnet run --project tools/UnicodeTableGenerator -- --version {version} --out PdfSharpCore/Text
//
//   The tool is deliberately outside PdfSharpCore.slnx: it runs by hand, and what it writes is
//   checked in so that the build needs no network and a version bump is a reviewable diff.
// </auto-generated>

namespace PdfSharpCore.Text;

/// <summary>
/// {summary}
/// </summary>
public enum {enumName} : {storage}
{{
");

    foreach (var name in names)
    {
        var member = MemberName(name, aliases, scriptCodes);
        var comment = member == name ? name : $"{name} ({aliases.GetValueOrDefault(name, "?")})";
        sb.Append($"    /// <summary>{comment}</summary>\r\n");
        sb.Append($"    {member} = {index[name]},\r\n\r\n");
    }

    sb.Length -= 2;
    sb.Append("}\r\n\r\n");

    sb.Append(@"static partial class UnicodeTables
{
");

    // Starts alone: the partition is complete, so a range ends where the next one begins and
    // storing both would be storing the same numbers twice.
    sb.Append($"    /// <summary>\r\n");
    sb.Append($"    /// The first code point of each run of equal {enumName}, ascending. A complete\r\n");
    sb.Append($"    /// partition of U+0000..U+10FFFF, defaults included, so every code point is in\r\n");
    sb.Append($"    /// exactly one run and a lookup is one binary search.\r\n");
    sb.Append($"    /// </summary>\r\n");
    sb.Append($"    internal static readonly int[] {enumName}RangeStart =\r\n    {{\r\n");
    sb.Append(Wrap(partition.Select(entry => "0x" + entry.First.ToString("X", CultureInfo.InvariantCulture))));
    sb.Append("    };\r\n\r\n");

    sb.Append($"    /// <summary>The value of each run of <see cref=\"{enumName}RangeStart\"/>.</summary>\r\n");
    sb.Append($"    internal static readonly {storage}[] {enumName}RangeValue =\r\n    {{\r\n");
    sb.Append(Wrap(partition.Select(entry => index[entry.Value].ToString(CultureInfo.InvariantCulture))));
    sb.Append("    };\r\n");

    if (scriptCodes)
    {
        sb.Append($"\r\n    /// <summary>\r\n");
        sb.Append($"    /// The ISO 15924 code of each <see cref=\"{enumName}\"/>, lowercased - the form a\r\n");
        sb.Append($"    /// shaper is told a run's script in.\r\n");
        sb.Append($"    /// </summary>\r\n");
        sb.Append($"    internal static readonly string[] {enumName}Code =\r\n    {{\r\n");
        sb.Append(Wrap(names.Select(name =>
            "\"" + aliases.GetValueOrDefault(name, "Zzzz").ToLowerInvariant() + "\"")));
        sb.Append("    };\r\n");
    }

    sb.Append("}\r\n");
    return sb.ToString();
}

static string MemberName(string name, Dictionary<string, string> aliases, bool scriptCodes)
{
    // Bidi classes are referred to by their abbreviations throughout UAX #9 - the rules are
    // written as "W2. Search backward ... until the first strong type (R, L, AL, or sos)" - so the
    // algorithm reads like the specification only if the enum does too. Scripts are the other way
    // round: nobody calls Arabic "Arab" in prose, and the code is carried separately.
    return scriptCodes ? name : aliases.GetValueOrDefault(name, name);
}

static string Wrap(IEnumerable<string> items)
{
    var sb = new StringBuilder();
    var line = new StringBuilder("        ");
    foreach (var item in items)
    {
        if (line.Length + item.Length + 2 > 100)
        {
            sb.Append(line.ToString().TrimEnd()).Append("\r\n");
            line = new StringBuilder("        ");
        }
        line.Append(item).Append(", ");
    }

    if (line.ToString().Trim().Length > 0)
        sb.Append(line.ToString().TrimEnd()).Append("\r\n");

    return sb.ToString();
}

static void Write(string path, string text)
{
    // Normalised on the way out. Some of the emitted text comes from verbatim string literals in
    // this file, so without this the generated tables would carry whatever line endings this
    // source happened to be checked out with - and regenerating on a differently configured
    // machine would produce a diff of the whole file and no change of substance.
    text = text.Replace("\r\n", "\n").Replace("\n", Environment.NewLine);

    File.WriteAllText(path, text, new UTF8Encoding(false));
    Console.WriteLine($"wrote {path} ({new FileInfo(path).Length} bytes)");
}

/// <summary>
/// A top-level local cannot be reached from a static local function, so the one constant the
/// whole program shares lives here.
/// </summary>
static class Ucd
{
    public const int MaxCodePoint = 0x10FFFF;
}
