<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTrimmable>true</IsTrimmable>
	<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	<ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfSharpCore\PdfSharpCore.csproj" />
	<TrimmerRootAssembly Include="PdfSharpCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfSharpCore.Skia\PdfSharpCore.Skia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.150.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="4.150.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.150.1" />
  </ItemGroup>

</Project>
