namespace MigraDocCore.DocumentObjectModel.Tests;

/// <summary>
///   The exact DDL <see cref="DdlByteComparisonHarnessTests"/> compares against, captured once from
///   a correct <c>Serialize</c> and pinned byte for byte - see that class's remarks for why. Built
///   with explicit <c>\r\n</c> escapes rather than embedded line breaks: <c>DdlWriter</c> always
///   writes CRLF, but this source file is committed under this repository's <c>text=auto</c>
///   normalisation, which would silently turn an embedded CRLF in a raw string literal into LF on a
///   platform that checks it out that way - CI runs on Linux - and the two golden strings would stop
///   matching what Windows-authored DDL produces for a reason that has nothing to do with a real
///   regression.
/// </summary>
internal static class Golden
{
    /// <summary>
    ///   The nine built-in heading styles and InvalidStyleName, written by every document that
    ///   names no other base for them - which is all six documents in the corpus but one, since
    ///   StyledParagraph adds a tenth style after this block rather than replacing it.
    /// </summary>
    static readonly string BuiltInStyles = string.Join("\r\n", new[]
    {
        "  \\styles",
        "  {",
        "    Heading1",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level1",
        "      }",
        "    }",
        "",
        "    Heading2",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level2",
        "      }",
        "    }",
        "",
        "    Heading3",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level3",
        "      }",
        "    }",
        "",
        "    Heading4",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level4",
        "      }",
        "    }",
        "",
        "    Heading5",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level5",
        "      }",
        "    }",
        "",
        "    Heading6",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level6",
        "      }",
        "    }",
        "",
        "    Heading7",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level7",
        "      }",
        "    }",
        "",
        "    Heading8",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level8",
        "      }",
        "    }",
        "",
        "    Heading9",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level9",
        "      }",
        "    }",
        "",
        "    InvalidStyleName",
        "    {",
        "      Font",
        "      {",
        "        Bold = true",
        "        Underline = Dash",
        "        Color = Lime",
        "      }",
        "    }",
        "  }",
    });

    public static readonly string NullableValuesSetAndUnset = string.Join("\r\n", new[]
    {
        "\\document",
        "[",
        "  Info",
        "  {",
        "    Title = \"A title\"",
        "  }",
        "  FootnoteStartingNumber = 7",
        "]",
        "{",
        BuiltInStyles,
        "  \\section",
        "  [",
        "    PageSetup",
        "    {",
        "      MirrorMargins = true",
        "      StartingNumber = 3",
        "    }",
        "  ]",
        "  {",
        "    \\paragraph",
        "    [",
        "      Format",
        "      {",
        "        Font",
        "        {",
        "          Name = \"Arial\"",
        "          Bold = true",
        "        }",
        "      }",
        "    ]",
        "    {",
        "      Hello",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string FormattedTextFont = string.Join("\r\n", new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\font[Name = \"Times New Roman\"",
        "    Size = 14",
        "    Bold = true",
        "    Italic = true",
        "    Underline = Dash",
        "    Strikethrough = Single",
        "    Superscript = true",
        "    Color = Firebrick",
        "    ]{text}",
        "  }",
        "}",
        "",
    });

    public static readonly string ClearedBordersAndShading = string.Join("\r\n", new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\paragraph",
        "    [",
        "      Format",
        "      {",
        "        Borders = null",
        "        Borders",
        "        {",
        "          Top",
        "          {",
        "            Width = 1",
        "          }",
        "        }",
        "        Shading = null",
        "      }",
        "    ]",
        "    {",
        "      Hello",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string Table = string.Join("\r\n", new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\table",
        "    [",
        "      Format",
        "      {",
        "        Alignment = Center",
        "      }",
        "      Borders",
        "      {",
        "        Width = 2",
        "      }",
        "      Shading",
        "      {",
        "        Color = LightGray",
        "      }",
        "    ]",
        "    {",
        "      \\columns",
        "      {",
        "        \\column",
        "        [",
        "          Width = \"3cm\"",
        "        ]",
        "        \\column",
        "        [",
        "          Width = \"4cm\"",
        "        ]",
        "      }",
        "      \\rows",
        "      {",
        "        \\row",
        "        {",
        "          \\cell",
        "          {",
        "            left",
        "          }",
        "          \\cell",
        "          {",
        "            right",
        "          }",
        "        }",
        "      }",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string Chart = string.Join("\r\n", new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\chart(Line)",
        "    {",
        "      \\series",
        "      {",
        "        1, 2, ",
        "      }",
        "      \\xvalues",
        "      {",
        "        \"one\", \"two\", ",
        "      }",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string StyledParagraph = string.Join("\r\n", new[]
    {
        "\\document",
        "{",
        "  \\styles",
        "  {",
        "    Heading1",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level1",
        "      }",
        "    }",
        "",
        "    Heading2",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level2",
        "      }",
        "    }",
        "",
        "    Heading3",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level3",
        "      }",
        "    }",
        "",
        "    Heading4",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level4",
        "      }",
        "    }",
        "",
        "    Heading5",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level5",
        "      }",
        "    }",
        "",
        "    Heading6",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level6",
        "      }",
        "    }",
        "",
        "    Heading7",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level7",
        "      }",
        "    }",
        "",
        "    Heading8",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level8",
        "      }",
        "    }",
        "",
        "    Heading9",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level9",
        "      }",
        "    }",
        "",
        "    InvalidStyleName",
        "    {",
        "      Font",
        "      {",
        "        Bold = true",
        "        Underline = Dash",
        "        Color = Lime",
        "      }",
        "    }",
        "",
        "    Loud : Normal",
        "    {",
        "      Font",
        "      {",
        "        Size = 20",
        "        Bold = true",
        "      }",
        "      ParagraphFormat",
        "      {",
        "        SpaceBefore = \"1cm\"",
        "      }",
        "    }",
        "  }",
        "  \\section",
        "  {",
        "    \\paragraph",
        "    [",
        "      Style = \"Loud\"",
        "      Format",
        "      {",
        "        Font",
        "        {",
        "          Italic = true",
        "        }",
        "      }",
        "    ]",
        "    {",
        "      styled",
        "    }",
        "  }",
        "}",
        "",
    });
}
