namespace MigraDocCore.DocumentObjectModel.Tests;

/// <summary>
///   The exact DDL <see cref="DdlByteComparisonHarnessTests"/> compares against, captured once from
///   a correct <c>Serialize</c> and pinned byte for byte - see that class's remarks for why. Joined
///   with <see cref="System.Environment.NewLine"/> rather than a hardcoded separator:
///   <c>DdlWriter.WriteToString</c> writes through a plain <c>StringWriter</c>, whose own
///   <c>NewLine</c> defaults to <c>Environment.NewLine</c> - CRLF on the Windows machine this was
///   captured on, LF on the Linux CI that runs it - so a golden value fixed to <c>\r\n</c> can never
///   match there. Each line is still a plain string with no embedded line break of its own, so
///   there is nothing for this repository's line-ending normalisation (<c>text=auto</c>) to disturb
///   either.
/// </summary>
internal static class Golden
{
    /// <summary>
    ///   The nine built-in heading styles and InvalidStyleName, written by every document that
    ///   names no other base for them - which is all six documents in the corpus but one, since
    ///   StyledParagraph adds a tenth style after this block rather than replacing it.
    /// </summary>
    static readonly string BuiltInStyles = string.Join(System.Environment.NewLine, new[]
    {
        "  \\styles",
        "  {",
        "    Heading1",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level1",
        "      }",
        "    }",
        "",
        "    Heading2",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level2",
        "      }",
        "    }",
        "",
        "    Heading3",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level3",
        "      }",
        "    }",
        "",
        "    Heading4",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level4",
        "      }",
        "    }",
        "",
        "    Heading5",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level5",
        "      }",
        "    }",
        "",
        "    Heading6",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level6",
        "      }",
        "    }",
        "",
        "    Heading7",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level7",
        "      }",
        "    }",
        "",
        "    Heading8",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level8",
        "      }",
        "    }",
        "",
        "    Heading9",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level9",
        "      }",
        "    }",
        "",
        "    InvalidStyleName",
        "    {",
        "      Font",
        "      {",
        "        Bold = true",
        "        Underline = Dash",
        "        Color = Lime",
        "      }",
        "    }",
        "  }",
    });

    public static readonly string NullableValuesSetAndUnset = string.Join(System.Environment.NewLine, new[]
    {
        "\\document",
        "[",
        "  Info",
        "  {",
        "    Title = \"A title\"",
        "  }",
        "  FootnoteStartingNumber = 7",
        "]",
        "{",
        BuiltInStyles,
        "  \\section",
        "  [",
        "    PageSetup",
        "    {",
        "      MirrorMargins = true",
        "      StartingNumber = 3",
        "    }",
        "  ]",
        "  {",
        "    \\paragraph",
        "    [",
        "      Format",
        "      {",
        "        Font",
        "        {",
        "          Name = \"Arial\"",
        "          Bold = true",
        "        }",
        "      }",
        "    ]",
        "    {",
        "      Hello",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string FormattedTextFont = string.Join(System.Environment.NewLine, new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\font[Name = \"Times New Roman\"",
        "    Size = 14",
        "    Bold = true",
        "    Italic = true",
        "    Underline = Dash",
        "    Strikethrough = Single",
        "    Superscript = true",
        "    Color = Firebrick",
        "    ]{text}",
        "  }",
        "}",
        "",
    });

    public static readonly string ClearedBordersAndShading = string.Join(System.Environment.NewLine, new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\paragraph",
        "    [",
        "      Format",
        "      {",
        "        Borders = null",
        "        Borders",
        "        {",
        "          Top",
        "          {",
        "            Width = 1",
        "          }",
        "        }",
        "        Shading = null",
        "      }",
        "    ]",
        "    {",
        "      Hello",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string Table = string.Join(System.Environment.NewLine, new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\table",
        "    [",
        "      Format",
        "      {",
        "        Alignment = Center",
        "      }",
        "      Borders",
        "      {",
        "        Width = 2",
        "      }",
        "      Shading",
        "      {",
        "        Color = LightGray",
        "      }",
        "    ]",
        "    {",
        "      \\columns",
        "      {",
        "        \\column",
        "        [",
        "          Width = \"3cm\"",
        "        ]",
        "        \\column",
        "        [",
        "          Width = \"4cm\"",
        "        ]",
        "      }",
        "      \\rows",
        "      {",
        "        \\row",
        "        {",
        "          \\cell",
        "          {",
        "            left",
        "          }",
        "          \\cell",
        "          {",
        "            right",
        "          }",
        "        }",
        "      }",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string Chart = string.Join(System.Environment.NewLine, new[]
    {
        "\\document",
        "{",
        BuiltInStyles,
        "  \\section",
        "  {",
        "    \\chart(Line)",
        "    {",
        "      \\series",
        "      {",
        "        1, 2, ",
        "      }",
        "      \\xvalues",
        "      {",
        "        \"one\", \"two\", ",
        "      }",
        "    }",
        "  }",
        "}",
        "",
    });

    public static readonly string StyledParagraph = string.Join(System.Environment.NewLine, new[]
    {
        "\\document",
        "{",
        "  \\styles",
        "  {",
        "    Heading1",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level1",
        "      }",
        "    }",
        "",
        "    Heading2",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level2",
        "      }",
        "    }",
        "",
        "    Heading3",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level3",
        "      }",
        "    }",
        "",
        "    Heading4",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level4",
        "      }",
        "    }",
        "",
        "    Heading5",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level5",
        "      }",
        "    }",
        "",
        "    Heading6",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level6",
        "      }",
        "    }",
        "",
        "    Heading7",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level7",
        "      }",
        "    }",
        "",
        "    Heading8",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level8",
        "      }",
        "    }",
        "",
        "    Heading9",
        "    {",
        "      ParagraphFormat",
        "      {",
        "        OutlineLevel = Level9",
        "      }",
        "    }",
        "",
        "    InvalidStyleName",
        "    {",
        "      Font",
        "      {",
        "        Bold = true",
        "        Underline = Dash",
        "        Color = Lime",
        "      }",
        "    }",
        "",
        "    Loud : Normal",
        "    {",
        "      Font",
        "      {",
        "        Size = 20",
        "        Bold = true",
        "      }",
        "      ParagraphFormat",
        "      {",
        "        SpaceBefore = \"1cm\"",
        "      }",
        "    }",
        "  }",
        "  \\section",
        "  {",
        "    \\paragraph",
        "    [",
        "      Style = \"Loud\"",
        "      Format",
        "      {",
        "        Font",
        "        {",
        "          Italic = true",
        "        }",
        "      }",
        "    ]",
        "    {",
        "      styled",
        "    }",
        "  }",
        "}",
        "",
    });
}
